jobs:
- max_in_flight: 1
  name: production
  plan:
  - get: dataworks-audit-data-ingest
    trigger: false
  - attempts: 15
    config:
      image_resource:
        source:
          repository: ((docker-awscli.repository))
          tag: ((docker-awscli.version))
          version: ((docker-awscli.version))
        type: docker-image
      outputs:
      - name: ssh-credentials
      params:
        AWS_DEFAULT_REGION: ((audit-ingest.aws_default_region))
        CLOUDHSM_KEY_ID: ((audit-ingest.cloudhsm_key_id))
        EDGENODE_USERNAME: ((audit-ingest.edgenode_username))
        HSM_KEY_PARAM_NAME: ((audit-ingest.hsm_key_param_name))
        PROXY: ((audit-ingest.internet_proxy))
        S3_BUCKET_ID: ((audit-ingest.s3_bucket_id))
        S3_PREFIX: ((audit-ingest.s3_prefix))
        SRC_HDFS_DIR: ((audit-ingest.src_hdfs_dir))
        SSH_PRIVATE_KEY: ((crown.private_key))
      platform: linux
      run:
        args:
        - -exc
        - |
          cat <<EOF> id_rsa
          $SSH_PRIVATE_KEY
          EOF
          cat <<EOF> ./config
          Host *
              User concourse
              StrictHostKeyChecking no
          EOF
          chmod 400 id_rsa
          cat <<EOF> wrapper.sh
          export HTTPS_PROXY="$PROXY"
          export https_proxy="$PROXY"
          sudo mkdir -p /home/$EDGENODE_USERNAME/.aws/
          sudo cp /tmp/credentials /home/$EDGENODE_USERNAME/.aws/
          sudo chown $EDGENODE_USERNAME:$EDGENODE_USERNAME /home/$EDGENODE_USERNAME/.aws/
          sudo -E su $EDGENODE_USERNAME -c 'python3 /tmp/audit_data_ingest.py \
              --src-hdfs-dir $SRC_HDFS_DIR \
              --s3-publish-bucket $S3_BUCKET_ID \
              --s3-prefix $S3_PREFIX \
              --hsm-key-id $CLOUDHSM_KEY_ID \
              --hsm-key-param-name $HSM_KEY_PARAM_NAME'
          EOF
        dir: ssh-credentials
        path: sh
    task: create-ssh-credentials
  - attempts: 15
    config:
      image_resource:
        source:
          repository: ((docker-awscli.repository))
          tag: ((docker-awscli.version))
          version: ((docker-awscli.version))
        type: docker-image
      outputs:
      - name: aws-session
      params:
        ASSUME_DURATION: 43200
        AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
        AWS_ACCOUNT: ((audit-ingest.aws_prod_account))
        AWS_DEFAULT_REGION: ((audit-ingest.aws_default_region))
        AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
      platform: linux
      run:
        args:
        - -exc
        - |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

          # obtain some form of AWS creds, lay down to file
          export AWS_ROLE_ARN=arn:aws:iam::$AWS_ACCOUNT:role/ci
          source /assume-role

          cat <<EOF> credentials
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          aws_session_token = $AWS_SESSION_TOKEN

          EOF

          unset AWS_ROLE_ARN
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
        dir: aws-session
        path: sh
    task: create-aws-credentials
  - config:
      image_resource:
        source:
          repository: ((docker-awscli-ubuntu.repository))
          tag: ((docker-awscli-ubuntu.version))
        type: docker-image
      inputs:
      - name: ssh-credentials
      - name: dataworks-audit-data-ingest
      params:
        EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))
      platform: linux
      run:
        args:
        - -exc
        - |
          cp -R ssh-credentials ~/.ssh
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no dataworks-audit-data-ingest/audit_data_ingest.py concourse@$EDGENODE_HOSTNAME:/tmp/
        path: sh
    task: deploy-code
  - config:
      image_resource:
        source:
          repository: ((docker-awscli-ubuntu.repository))
          tag: ((docker-awscli-ubuntu.version))
        type: docker-image
      inputs:
      - name: ssh-credentials
      params:
        EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))
        EDGENODE_USERNAME: ((audit-ingest.edgenode_username))
      platform: linux
      run:
        args:
        - -exc
        - |
          cp -R ssh-credentials ~/.ssh
          ssh -o StrictHostKeyChecking=no concourse@$EDGENODE_HOSTNAME "sudo su - $EDGENODE_USERNAME -c 'kinit -kt /home/$EDGENODE_USERNAME/$EDGENODE_USERNAME.keytab $EDGENODE_USERNAME@DW'"
        path: sh
    task: kinit
  - config:
      image_resource:
        source:
          repository: ((docker-awscli-ubuntu.repository))
          tag: ((docker-awscli-ubuntu.version))
        type: docker-image
      inputs:
      - name: ssh-credentials
      - name: aws-session
      - name: dataworks-audit-data-ingest
      params:
        EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))
        EDGENODE_USERNAME: ((audit-ingest.edgenode_username))
      platform: linux
      run:
        args:
        - -exc
        - |
          cp -R ssh-credentials ~/.ssh
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no aws-session/credentials concourse@$EDGENODE_HOSTNAME:/tmp/
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ssh-credentials/wrapper.sh concourse@$EDGENODE_HOSTNAME:/tmp/
          ssh -o StrictHostKeyChecking=no concourse@$EDGENODE_HOSTNAME "bash +x /tmp/wrapper.sh"
        path: sh
    task: execute-code
resources:
- check_every: 5m
  name: dataworks-audit-data-ingest
  source:
    branch: dw5219_create_concourse_pipelines
    repository: dwp/dataworks-audit-data-ingest
    uri: https://github.com/dwp/dataworks-audit-data-ingest.git
  type: git
  webhook_token: ((dataworks.concourse_github_webhook_token))
