jobs:
  - name: production
    max_in_flight: 1
    plan:
#      - get: 12h
#        trigger: true
      - get: dataworks-audit-data-ingest
        trigger: false
      - .: (( inject meta.plan.create-ssh-credentials ))
        config:
          params:
            SSH_PRIVATE_KEY: ((crown.private_key))
            PROXY: ((audit-ingest.internet_proxy))
            EDGENODE_USERNAME: ((audit-ingest.edgenode_username))
            CLOUDHSM_KEY_ID: ((audit-ingest.cloudhsm_key_id))
            HSM_KEY_PARAM_NAME: ((audit-ingest.hsm_key_param_name))
            S3_BUCKET_ID: ((audit-ingest.s3_bucket_id))
            S3_PREFIX: ((audit-ingest.s3_prefix))
            SRC_HDFS_DIR: ((audit-ingest.src_hdfs_dir))
            AWS_DEFAULT_REGION: ((audit-ingest.aws_default_region))

      - .: (( inject meta.plan.create-aws-credentials ))
        config:
          params:
            AWS_ACCOUNT: ((audit-ingest.aws_prod_account))
            AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
            AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
            AWS_DEFAULT_REGION: ((audit-ingest.aws_default_region))
            ASSUME_DURATION: 43200

      - .: (( inject meta.plan.deploy-code ))
        config:
          params:
            EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))


      - .: (( inject meta.plan.kinit ))
        config:
          params:
            EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))
            EDGENODE_USERNAME: ((audit-ingest.edgenode_username))

      - .: (( inject meta.plan.execute-code ))
        config:
          params:
            EDGENODE_HOSTNAME: ((audit-ingest.edgenode_hostname))
            EDGENODE_USERNAME: ((audit-ingest.edgenode_username))

