meta:
  plan:
    kinit:
      task: kinit
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker-awscli-ubuntu.repository))
            tag: ((docker-awscli-ubuntu.version))
        run:
          path: sh
          args:
            - -exc
            - |
              cp -R ssh-credentials ~/.ssh
              ssh -o StrictHostKeyChecking=no $EDGENODE_HOSTNAME "sudo su - $EDGENODE_USERNAME -c 'kinit -kt /home/$EDGENODE_USERNAME/$EDGENODE_USERNAME.keytab $EDGENODE_USERNAME@DW'"
        inputs:
          - name: ssh-credentials

    deploy-code:
      task: deploy-code
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker-awscli-ubuntu.repository))
            tag: ((docker-awscli-ubuntu.version))
        run:
          path: sh
          args:
            - -exc
            - |
              cp -R ssh-credentials ~/.ssh
              scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no dataworks-audit-data-ingest/audit_data_ingest.py $EDGENODE_HOSTNAME:/tmp/
        inputs:
          - name: ssh-credentials
          - name: dataworks-audit-data-ingest

    execute-code:
      task: execute-code
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker-awscli-ubuntu.repository))
            tag: ((docker-awscli-ubuntu.version))
        run:
          path: sh
          args:
            - -exc
            - |
              cp -R ssh-credentials ~/.ssh
              ssh -o StrictHostKeyChecking=no $EDGENODE_HOSTNAME "sudo su - $EDGENODE_USERNAME -c '/tmp/audit_data_ingest.py \
                  --src-hdfs-dir $SRC_HDFS_DIR \
                  --s3-publish-bucket $S3_PUBLISH_BUCKET \
                  --s3-prefix $S3_PREFIX \
                  --hsm-key-id $CLOUDHSM_KEY_ID"
        inputs:
          - name: ssh-credentials
          - name: dataworks-audit-data-ingest

    create-crown-credentials:
      task: create-crown-credentials
      attempts: 15
      input_mapping:
        git-repo: dataworks-audit-data-ingest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker-awscli-ubuntu.repository))
            version: ((docker-awscli-ubuntu.version))
            tag: ((docker-awscli-ubuntu.version))
        inputs:
          - name: git-repo
        outputs:
          - name: ssh-credentials
        run:
          path: sh
          dir: ssh-credentials
          args:
            - -exc
            - |
              cat <<EOF> id_rsa
              $PRIVATE_KEY
              EOF
              cat <<EOF> ./config
              Host *
                  User concourse
                  StrictHostKeyChecking no
              EOF
              chmod 400 id_rsa
